name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd apps/web && npm ci
        cd ../.. && cd services/api && npm ci
        cd ../.. && cd workers/renderer && npm ci

    - name: Lint code
      run: |
        cd apps/web && npm run lint
        cd ../.. && cd services/api && npm run lint || echo "No lint script"
        cd ../.. && cd workers/renderer && npm run lint || echo "No lint script"

    - name: Build projects
      run: |
        cd apps/web && npm run build
        cd ../.. && cd services/api && npm run build
        cd ../.. && cd workers/renderer && npm run build

    - name: Run tests
      run: |
        cd apps/web && npm test || echo "No tests found"
        cd ../.. && cd services/api && npm test || echo "No tests found"
        cd ../.. && cd workers/renderer && npm test || echo "No tests found"

  build-images:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'push'
    
    strategy:
      matrix:
        service: [web, api, renderer]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.service }}-

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.service == 'web' && 'apps/web' || matrix.service == 'api' && 'services/api' || 'workers/renderer' }}
        push: false
        tags: immersalab-${{ matrix.service }}:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache